server:
  port: 8000

spring:
  application:
    name: school-server
  cloud:
    nacos:
      discovery:
        server-addr: 47.97.163.73:8848
#  rabbitmq:
#    host: 127.0.0.1
#    port: 5672
#    username: guest
#    password: guest
#    virtualHost: /
feign:
  client:
    config:
      default:
        connectTimeout: 60000
        readTimeout: 10000